# Generated by Django 2.2.13 on 2020-11-07 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonList',
            fields=[
                ('Id', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=30)),
                ('Email', models.EmailField(max_length=30, unique=True)),
                ('Password', models.CharField(max_length=30)),
            ],
        ),
    ]
